version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:4.2.1-bionic
    ports:
      - "27018:27017"
    networks:
      - backend
  app:
    container_name: ts-node-app
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment: 
      - MONGODB_URL=mongodb://mongo:27017/node-boilerplate
      - CLIENT_URL=${CLIENT_URL}
      - RABBITMQ_URL=amqp://rabbitmq:5672
    links: 
      - mongo
      - rabbitmq
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - backend

networks:
  backend:
    driver: bridge    
